# Generated by Django 3.2.8 on 2021-10-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='desc',
            field=models.TextField(max_length=255),
        ),
    ]
