# Generated by Django 3.2.8 on 2021-10-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20211018_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='desc',
            field=models.TextField(),
        ),
    ]
