# Generated by Django 3.2.8 on 2021-11-11 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20211018_0204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='lisiting',
            new_name='listing',
        ),
    ]
