# Generated by Django 3.2.8 on 2021-12-14 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20211213_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='listingid',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='userid',
            new_name='user',
        ),
    ]
