# Generated by Django 3.2.8 on 2021-12-15 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_remove_highestbid_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highestbid',
            name='id',
        ),
        migrations.AlterField(
            model_name='highestbid',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auctions.listing'),
        ),
    ]
